// Mocks generated by Mockito 5.4.6 from annotations
// in newpro/test/blocs/chat_conversation_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:newpro/models/message.dart' as _i5;
import 'package:newpro/models/message_response.dart' as _i2;
import 'package:newpro/services/message_service.dart' as _i3;
import 'package:newpro/services/socket_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageResponse_0 extends _i1.SmartFake
    implements _i2.MessageResponse {
  _FakeMessageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageService extends _i1.Mock implements _i3.MessageService {
  MockMessageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Message>> getChatMessages(
    String? chatId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [chatId, currentUserId]),
            returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
          )
          as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<_i2.MessageResponse> sendMessage({
    required String? chatId,
    required String? senderId,
    required String? content,
    required String? messageType,
    String? fileUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatId: chatId,
              #senderId: senderId,
              #content: content,
              #messageType: messageType,
              #fileUrl: fileUrl,
            }),
            returnValue: _i4.Future<_i2.MessageResponse>.value(
              _FakeMessageResponse_0(
                this,
                Invocation.method(#sendMessage, [], {
                  #chatId: chatId,
                  #senderId: senderId,
                  #content: content,
                  #messageType: messageType,
                  #fileUrl: fileUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MessageResponse>);
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i6.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.ConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i4.Stream<_i6.ConnectionStatus>.empty(),
          )
          as _i4.Stream<_i6.ConnectionStatus>);

  @override
  _i4.Stream<_i5.Message> get messageReceived =>
      (super.noSuchMethod(
            Invocation.getter(#messageReceived),
            returnValue: _i4.Stream<_i5.Message>.empty(),
          )
          as _i4.Stream<_i5.Message>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  void connect(String? userId) => super.noSuchMethod(
    Invocation.method(#connect, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(String? event, dynamic data) => super.noSuchMethod(
    Invocation.method(#emit, [event, data]),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
